# Header
menu:
  Home: http://www.ingress.pub/
  Meet: https://ingress.pub/meet
  Missions: http://missions.ingress.pub/
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# Miscellaneous
google_analytics:
favicon: /images/logo.png
twitter:
google_plus: https://plus.google.com/+SgrAlphaPlus
fb_admins:
fb_app_id: